### ISSUE TITLE
fmt is out of date on the build machine

### ISSUE THREAD

**Issue by seanfarley** [clasp-developers/homebrew-clasp#320]
Installing from this afternoon, I get the following missing link:

```
$ clasp
dyld[96762]: Library not loaded: /usr/local/opt/fmt/lib/libfmt.9.dylib
  Referenced from: <2926885E-1ADF-3647-8604-610799786C7A> /usr/local/Cellar/clasp-cl/2.2.0-175-g5c9f7ed83/bin/iclasp
  Reason: tried: '/usr/local/opt/fmt/lib/libfmt.9.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/fmt/lib/libfmt.9.dylib' (no such file), '/usr/local/opt/fmt/lib/libfmt.9.dylib' (no such file), '/usr/local/lib/libfmt.9.dylib' (no such file), '/usr/lib/libfmt.9.dylib' (no such file, not in dyld cache), '/usr/local/Cellar/fmt/10.0.0/lib/libfmt.9.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/fmt/10.0.0/lib/libfmt.9.dylib' (no such file), '/usr/local/Cellar/fmt/10.0.0/lib/libfmt.9.dylib' (no such file), '/usr/local/lib/libfmt.9.dylib' (no such file), '/usr/lib/libfmt.9.dylib' (no such file, not in dyld cache)
zsh: abort      clasp
```

Looking at homebrew's updates it seems `fmt` was updated to version 10 last week. Could the bottle build machines be updated so that the newest versions of the libraries are used? Thanks!

**Comment by yitzchak** [comment]
The bottles haven't been built for about 4 days because i appears there is a bug in the most recent fmt on homebrew. I'm looking for a work-around but I haven't found one yet.

**Comment by seanfarley** [comment]
Ah, I see! Thanks for the insight into the problem!

**Comment by yitzchak** [comment]
I submitted an issue for what I think is happening https://github.com/fmtlib/fmt/issues/3472

**Comment by seanfarley** [comment]
Oh, that's really awesome; I wouldn't have been able to guess that!

**Comment by yitzchak** [comment]
New bottles have been published

**Comment by seanfarley** [comment]
Woo!
